dist: trusty

services: docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make clean
  - make build
  - make push

env:
  - DOCKER_USERNAME=julienescueta
  matrix:
    secure: "Hlo1Ym6RUCeVavhdt7NsvN2XRsJhSeUZR4ssdKVI6c96ZbGS9juG8QGngOfReuazXlK0Vlcr+nY+vp//Y07NqBV8kSBBbBN2Ve1yYwQpyh/5FORs8hfK7ROrQmu4MOXzl32WKmvu9SwtQL+LqZGc49VQG8xSG/u0nr2cNttbN9ChR9zy240We08rfw6fIKLyycl6tcPiigVILg5wf7+ssEKrG25FvTwn4eb2B4iivL9JDvS47rw4cCz+Fh7vibhq1B0dNj5+FLYRL+AYCTIDj9v9VOEW8hD5F+tker6GS4Va8oyEFtAXbUP2pUhHxOA6wkTn+FMdnvaSws5LRgy10qnddySGC26AkYVlCqvgDuhswL5aoLdUZpHnTh+nK+jWnmvJM/MKEsLPwQLngCjlVT5oBkSxLUyBnorQLmYAw8u9ndaskGWvZkSjkL7kDm0JAtVjrVAn+o6YYM/pfAXLhm2RKNJ+NNgjFDew2oUAvj8iJd151aPY2sj/H1+5KKENI9+Lc7eT/FJbFmLEqGCNdYf4EEizH/LPe28L0f9HilFTTR/R1JHBVdesDflzk/1VXFw0TbApH0dD0BsqKF49XufWQ/lmg4PEQxI2SBA2y0ZFGgHEUC1nOKaggEwE305ulCjMG/i8zkaT3OlyPFiJ4+OiJeIiaH4AE9IknRREFoc="
