version: '3.6'

services:
  api:
    image: julienescueta/identifier-service
    ports:
      - 80:3030
    networks:
      - identifier
    depends_on:
      - database

  database:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=api
    networks:
      - identifier
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

networks:
  identifier:
